# this is a basic workfolw to help you get started with Actions
name: CI

# Controls when the action will run.

on:
  # Triggers the workflow on push or pull request events only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the actions tab
  workflow_dispatch:
  
  
jobs:
